  
version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 50
    versioning-strategy: increase
  - package-ecosystem: "npm"
    schedule:
      interval: "weekly"
