name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install NodeJs 
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install
      run: npm ci
    - name: Build
      run: npm run build
    - name: Test
      run: npm run testci
